export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const GET_LOGIN_USER_DETAIL_REQUEST = "GET_LOGIN_USER_DETAIL_REQUEST";
export const GET_LOGIN_USER_DETAIL_SUCCESS = "GET_LOGIN_USER_DETAIL_SUCCESS";
export const GET_LOGIN_USER_DETAIL_FAIL = "GET_LOGIN_USER_DETAIL_FAIL";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const BOOK_APPOINTMENT_REQUEST = "BOOK_APPOINTMENT_REQUEST";
export const BOOK_APPOINTMENT_SUCCESS = "BOOK_APPOINTMENT_SUCCESS";
export const BOOK_APPOINTMENT_FAIL = "BOOK_APPOINTMENT_FAIL";

export const GET_MY_APPOINTMENT_REQUEST = "GET_MY_APPOINTMENT_REQUEST";
export const GET_MY_APPOINTMENT_SUCCESS = "GET_MY_APPOINTMENT_SUCCESS";
export const GET_MY_APPOINTMENT_FAIL = "GET_MY_APPOINTMENT_FAIL";

export const CANCEL_APPOINTMENT_REQUEST = "CANCEL_APPOINTMENT_REQUEST";
export const CANCEL_APPOINTMENT_SUCCESS = "CANCEL_APPOINTMENT_SUCCESS";
export const CANCEL_APPOINTMENT_FAIL = "CANCEL_APPOINTMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGE";